version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - "15432:5432"
    # volumes:
    #   - ./database:/var/lib/postgresql/data
    networks: 
      - network_zap
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres_password
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks: 
      - network_zap
  hasura:
    restart: always
    build:
      context: ./hasura
    ports:
      - "1337:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres_password@postgres:5432/postgres # postgresql defaults
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      # - HASURA_GRAPHQL_ADMIN_SECRET=jkasvbdhbjaasdkahbsd
    depends_on:
      - postgres
      - pgadmin
    networks: 
      - network_zap
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks: 
      - network_zap
  s3:
    image: minio/minio
    command: server http://minio{1...4}/data{1...2}
    ports:
      - "9000:9000"
    volumes:
      - ./storage:/data
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    command: server /data
    networks: 
      - network_zap
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - ENCRYPTION_KEY=asdfsdaf
      - DATABASE_URL=postgres://postgres:postgres_password@postgres:5432/postgres # postgresql defaults
      - CLOUDINARY_URL=dfadfasdf
      - PORT=8010
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    networks: 
      - network_zap
  site:
    build:
      context: ./site
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SERVER_URL=http://localhost:1337/v1/graphql
      - REACT_APP_AUTH_URL=http://localhost:8010
      - REACT_APP_ENV="dev"
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - server
    volumes:
      - ./site:/app
    networks: 
      - network_zap

networks:
  network_zap:
    driver: bridge